### ISSUE TITLE
Check for error dialogs and close them

### ISSUE THREAD

**Issue by aequasi** [highvoltz/HBRelog#4]
Every once in awhile, wow will get a dialog that direct 3d or something could start, and then hangs the entire hbrelog process until i close the dialog. Would be nice if that got closed.

**Comment by aash** [comment]
The issue description is uniformative. Please provide screenshot, logs and details on how to reproduce it.

**Comment by aequasi** [comment]
I'll post a screenshot the next time i see it. The error is this: https://us.battle.net/support/en/article/world-of-warcraft-was-unable-to-start-up-3d-acceleration

Its a modal window. I have no idea how to reproduce it.

**Comment by aequasi** [comment]
http://screencast.com/t/xDsz2d4iSFh

**Comment by aequasi** [comment]
And no logs to send. Nothing is happening, its just "Waiting for wow to start"

**Comment by aash** [comment]
Okay, understood. It can be fixed. I will try to implement it in my fork.

**Comment by aash** [comment]
Are you still got this issue?
I can't reproduce it. Can you tell me the exact caption of the dialogue?

**Comment by aequasi** [comment]
Yeah, all the time. 

I posted the link that has the message.

> World of Warcraft was unable to start up 3D acceleration. Please make sure DirectX 9.0 is installed and your video drivers are up-to-date.

**Comment by aash** [comment]
Ok. Thank you.

**Comment by aash** [comment]
Ok, Got it fixed, in my local repository. Can you copy this issue to my fork?
