### ISSUE TITLE
using .bat file to launch wow, hbrelog doesnt detect the new wow process.

### ISSUE THREAD

**Issue by hansskogvold** [highvoltz/HBRelog#7]
`@ECHO OFF`
`:some stuff`
`start "WoW" "D:\Games\World of Warcraft\Wow.exe"`
`:some other stuff`
`exit`

i have deleted the Wow-64.exe from the World of Warcraft folder.

Log output when starting profile in hbrelog:
[23:05:05] Mining#1: ********* End of Task list ***********
[23:05:06] Mining#1: Warning: Unable to find Wow's config.wtf file. Editing this file speeds up the login process.
[23:05:06] Mining#1: Starting D:\Programs\HBRelog\REALID\start.bat
[23:05:07] Mining#1: Waiting on external application to start WoW

wow window opens but hbrelog never logs in or launches hb

**Comment by aash** [comment]
Why do you use bat file to start wow? Is it because you want to do some staff just before or after wow starts?

**Comment by hansskogvold** [comment]
exactly. the wow executable field says it supports bat files and I have
read about other people using it

**Comment by aash** [comment]
Where's a full log?

**Comment by hansskogvold** [comment]
Full log: http://pastebin.com/ZA67bevd

**Comment by hansskogvold** [comment]
Updated to hbrelog 1.1.3 and still same issue

**Comment by highvoltz** [comment]
Try passing passing the command-line argument  '-noautolaunch64bit' to WoW.

**Comment by highvoltz** [comment]
A simple batch file with the following line works for me.
"F:\World of Warcraft\WoW.exe" "-noautolaunch64bit"

**Comment by hansskogvold** [comment]
Ah, I was using `start "WoW" "D:\Games\World of Warcraft\Wow.exe" "-noautolaunch64bit"`,
when i changed it to just the path and the parameter it would work. Thanks and sorry for the false alarm :+1:
